### ISSUE TITLE
add --order parameter to storm list command

### ISSUE THREAD

**Issue by emre** [emre/storm#6]

**Comment by GreatBahram** [comment]
Hi @emre 
there is problem with this program, for example image somebody has its config file and into that file it has one generic config and two client config. Then he decides to use stormssh to makes his life easier.
Now he tried to add new host, Stormssh add this new host at the end of config file, So what is the problem ? 
since you added to end of the file, whenever he/she tries to ssh to that new client all generic options will be used  by ssh? Why ? 'Cause order is important on ssh config file.
Thanks
